### ISSUE TITLE
Wrong Callsign

### ISSUE THREAD

**Issue by Chrisoo** [mutability/mlat-server#1]
For most aircraft displays the wrong callsign (aircraft sends valid) or it is not there. 
Knowing one letter or number is incorrect.

**Comment by mutability** [comment]
Can you give an example? (Ideally with the raw message that has the right callsign)

**Comment by Chrisoo** [comment]
MLAT 
http://screenshot.sh/ovqKCuMdxzUPX

RAW
http://screenshot.sh/oeLMedoGIxeUd
http://screenshot.sh/n7kC6vc43DJFj
http://screenshot.sh/m8sN48IvtQl8R

**Comment by mutability** [comment]
Try 7a23912b7267f875f1f34ef0d01be8cd3e7ab7f4 and let me know if that fixes it?

**Comment by Chrisoo** [comment]
Now displaying correctly. 
Thanks

**Comment by mutability** [comment]
Thanks for the report :)
