### ISSUE TITLE
Jumping/jagged tracking

### ISSUE THREAD

**Issue by Chrisoo** [mutability/mlat-server#10]
Hi
When I use my mlat-server is tracking is jagged with jumps http://screenshot.sh/m1CmWCqce1Lac
Such jagged is not in results from FA.

**Comment by Chrisoo** [comment]
Again I ask a question, Would it be possible to fix these jumping/jagged tracking?
https://scr.hu/KzBBdj

**Comment by mutability** [comment]
FA has a much better solver than the public code, so.. you'd need to improve the solver.

**Comment by Chrisoo** [comment]
Can you improve this solver in mlat-server?

**Comment by mutability** [comment]
I'm not currently working on mlat-server in my limited spare time. I'll take PRs though.

**Comment by Chrisoo** [comment]
Can you now have the time to correct this mistake?

**Comment by mutability** [comment]
No, I do not have spare time to work on mlat-server. please stop asking.
