### ISSUE TITLE
No module named 'pykalman'

### ISSUE THREAD

**Issue by stelmaszyk** [mutability/mlat-server#16]
I tried everything I thing. Installed via pip, pip3, conda.. Without effect. What's going on?

**Comment by mutability** [comment]
https://github.com/pykalman/pykalman

**Comment by mutability** [comment]
(I mean, I assume you tried installing it and couldn't find it. If you installed it and the module's still not found, you probably have a mismatch between the python install you're using for mlat-server and the python install that pip3 et al are installing for. either way - it's not a problem that I can do anything about)
