### ISSUE TITLE
Wrong Altitude

### ISSUE THREAD

**Issue by Chrisoo** [mutability/mlat-server#2]
Why shows the wrong altitude?
http://screenshot.sh/ovTH2kNjqVui4

**Comment by mutability** [comment]
Not transmitting mode S altitude (or not being interrogated), and ground based mlat is bad at finding altitude. There are two plausible solutions and the current solver often picks the one below the earth's surface, not above it.

**Comment by Chrisoo** [comment]
It can be done so as to correctly showed as in FR24?
http://screenshot.sh/mFZUYKmnIHLxc

**Comment by mutability** [comment]
Sure. Patches to improve the solver are welcome.

**Comment by Chrisoo** [comment]
Sorry, bad I expressed ;-)
Can you fix it as it is on the FR24?

**Comment by mutability** [comment]
It's on my todo list, but low priority as it does not affect many aircraft.

**Comment by Chrisoo** [comment]
ok, thanks

**Comment by Chrisoo** [comment]
It may have already tried to fix it?
I noticed that this error occurs only in military machines.
