### ISSUE TITLE
Ghost hex

### ISSUE THREAD

**Issue by Chrisoo** [mutability/mlat-server#7]
Hi
A lot appears hexes ghost. I always position shown side by side.
The following screenshot of the case:
http://screenshot.sh/mKBhtdz6m6NOY
And it appears in the results of the mlat-server.

**Comment by mutability** [comment]
Sounds like bad input data. What is your receiver configuration? If you use --aggressive, turn it off.

**Comment by Chrisoo** [comment]
I have connected about 100 receivers and do not know what is the configuration of the other receivers.

**Comment by mutability** [comment]
What mlat-client version are you using?

**Comment by Chrisoo** [comment]
0.2.5 dev

**Comment by mutability** [comment]
That is a wide range of code. What's the commit hash you're on?

I am particularly interested in whether you have this commit included: https://github.com/mutability/mlat-client/commit/7f25d8eb432760674db96e1c09aa9a7e090fab3c

**Comment by Chrisoo** [comment]
I have a version of 2 March

**Comment by mutability** [comment]
OK, so mlat-client isn't contributing to the problem, it's just that you have bad data from your receivers.

**Comment by Chrisoo** [comment]
I noticed another relationship, these empty hexes they appear behind him true hex
http://screenshot.sh/m7hU7HMCFQk8E

**Comment by Chrisoo** [comment]
When connected about 100 receivers how to verify that the receiver sends bad data?
